# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LiC9C9j7F2oK-Njd_C28NRg7K375qiqY
"""

#setting up the required libraries
#Load the data
#preprocessing if you want
#Train your model
#do predictions
#check the accuracy
#Plot results using data visualization libraries

import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score
import matplotlib.pyplot as plt

data_dict ={
    "Time": [5,10,15,20,25,30,35,40,45,50],
    "Temperature(C)": [25.3, 28.2,21.3, 27.3,22.1, 21.3,28.9, 24.3,21.2, 20.3,]
}

data = pd.DataFrame(data_dict)

data.head()

data['Temp_Diff'] = data['Temperature(C)'].diff().fillna(0)

data['Overheating'] = np.where(data['Temperature(C)'] >28, 1,0)
X = data[['Temperature(C)' , 'Temp_Diff']]
y = data['Overheating']

X_tain, X_test, y_train, y_test = train_test_split(X,y, test_size=0.2, random_state=40)
model = DecisionTreeClassifier(max_depth=3)
model.fit(X_tain, y_train) # THIS IS THE COD

y_pred = model.predict(X_test)

accuracy = accuracy_score(y_test, y_pred)
print (accuracy)

new_data = pd.DataFrame({
    "Temperature(C)": [29.5,30.5,32.0],
    "Temp_Diff": [1.3, 2.1,1.5]
})

predictions = model.predict(new_data)
for temp, pred in zip(new_data['Temperature(C)'], predictions):
  print(f"Temp: {temp} C -> {'Overheating'}")

plt.plot(data['Time'], data['Temperature(C)'], label='Temperature')
plt.axhline(y=30, color='r', linestyle='--', label='Overheating Threshold')
plt.xlabel('Time(s)')
plt.ylabel('Temperature(C)')